#!/bin/sh

state() {

  is_powered=$(bluetoothctl show | grep Powered | awk -F ': ' '{print $2}')
  device=$(bluetoothctl devices Connected) 

  if [ "$is_powered" = "yes" ] && [ "$device" ]; then 
    echo connected
  elif [ "$is_powered" = "yes" ]; then 
    echo on
  else
    echo off
  fi

}

device() {
  bluetoothctl devices Connected | cut -d " " -f 3-
}

[ "$1" = "state" ] && state && exit
[ "$1" = "device" ] && device && exit




