#!/usr/bin/env bash

spaces (){
	WORKSPACE_INFO=$(hyprctl workspaces -j | jq 'map({key: .id | tostring | tostring, value: {windows: .windows, title: .lastwindowtitle}}) | from_entries')
	seq 1 10 | jq --argjson windows "${WORKSPACE_INFO}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.].windows//0), title: ($windows[.].title//"")})'
}

spaces
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	spaces
done
