#!/bin/sh

state() {
  state=$(nmcli radio wifi)
  connection=$(nmcli connection show --active | grep "wifi" | cut -d " " -f1)
  if [ "$state" = "enabled" ] && [ "$connection" ]; then
    echo connected
  elif [ "$state" = "enabled" ]; then
    echo nonetwork
  else
    echo disabled
  fi
}

ssid() {
nmcli connection show --active | grep "wifi" | cut -d " " -f1
}

[ "$1" = "state" ] && state && exit
[ "$1" = "ssid" ] && ssid && exit
